package sop_corba;


/**
* sop_corba/_ClienteIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

public class _ClienteIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.ClienteInt
{

  public boolean registarUsuario (sop_corba.datosUsuarios valores)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registarUsuario", true);
                sop_corba.dtUsuHelper.write ($out, valores);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registarUsuario (valores        );
            } finally {
                _releaseReply ($in);
            }
  } // registarUsuario

  public void modificarUsuarioU (String login)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modificarUsuarioU", true);
                $out.write_string (login);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modificarUsuarioU (login        );
            } finally {
                _releaseReply ($in);
            }
  } // modificarUsuarioU

  public void consultarCancionesTitulo (String titulo, sop_corba.datosCancionesHolder valores)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarCancionesTitulo", true);
                $out.write_string (titulo);
                $in = _invoke ($out);
                valores.value = sop_corba.dtCancHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                consultarCancionesTitulo (titulo, valores        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarCancionesTitulo

  public void consultarCancionesCantante (String cantante, sop_corba.datosCancionesHolder valores)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarCancionesCantante", true);
                $out.write_string (cantante);
                $in = _invoke ($out);
                valores.value = sop_corba.dtCancHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                consultarCancionesCantante (cantante, valores        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarCancionesCantante

  public boolean crearListasReproduccion (String login, String nombrelista, sop_corba.datosCanciones valores)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearListasReproduccion", true);
                $out.write_string (login);
                $out.write_string (nombrelista);
                sop_corba.dtCancHelper.write ($out, valores);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearListasReproduccion (login, nombrelista, valores        );
            } finally {
                _releaseReply ($in);
            }
  } // crearListasReproduccion

  public void mostrarListasReproduccion (sop_corba.ClienteIntPackage.listaReproducionHolder valores)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mostrarListasReproduccion", true);
                $in = _invoke ($out);
                valores.value = sop_corba.ClienteIntPackage.dtListaCancHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                mostrarListasReproduccion (valores        );
            } finally {
                _releaseReply ($in);
            }
  } // mostrarListasReproduccion

  public boolean borrarCancionLista (String nombreCancion, String nombreLista)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("borrarCancionLista", true);
                $out.write_string (nombreCancion);
                $out.write_string (nombreLista);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return borrarCancionLista (nombreCancion, nombreLista        );
            } finally {
                _releaseReply ($in);
            }
  } // borrarCancionLista

  public void enviarMensaje (String usuario, String mensaje)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarMensaje", true);
                $out.write_string (usuario);
                $out.write_string (mensaje);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enviarMensaje (usuario, mensaje        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarMensaje

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ClienteInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClienteIntStub
