package sop_corba;


/**
* sop_corba/ClienteIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

public abstract class ClienteIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.ClienteIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registarUsuario", new java.lang.Integer (0));
    _methods.put ("modificarUsuarioU", new java.lang.Integer (1));
    _methods.put ("consultarCancionesTitulo", new java.lang.Integer (2));
    _methods.put ("consultarCancionesCantante", new java.lang.Integer (3));
    _methods.put ("crearListasReproduccion", new java.lang.Integer (4));
    _methods.put ("mostrarListasReproduccion", new java.lang.Integer (5));
    _methods.put ("borrarCancionLista", new java.lang.Integer (6));
    _methods.put ("enviarMensaje", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/ClienteInt/registarUsuario
       {
         sop_corba.datosUsuarios valores = sop_corba.dtUsuHelper.read (in);
         boolean $result = false;
         $result = this.registarUsuario (valores);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/ClienteInt/modificarUsuarioU
       {
         String login = in.read_string ();
         this.modificarUsuarioU (login);
         out = $rh.createReply();
         break;
       }

       case 2:  // sop_corba/ClienteInt/consultarCancionesTitulo
       {
         String titulo = in.read_string ();
         sop_corba.datosCancionesHolder valores = new sop_corba.datosCancionesHolder ();
         this.consultarCancionesTitulo (titulo, valores);
         out = $rh.createReply();
         sop_corba.dtCancHelper.write (out, valores.value);
         break;
       }

       case 3:  // sop_corba/ClienteInt/consultarCancionesCantante
       {
         String cantante = in.read_string ();
         sop_corba.datosCancionesHolder valores = new sop_corba.datosCancionesHolder ();
         this.consultarCancionesCantante (cantante, valores);
         out = $rh.createReply();
         sop_corba.dtCancHelper.write (out, valores.value);
         break;
       }

       case 4:  // sop_corba/ClienteInt/crearListasReproduccion
       {
         String login = in.read_string ();
         String nombrelista = in.read_string ();
         sop_corba.datosCanciones valores = sop_corba.dtCancHelper.read (in);
         boolean $result = false;
         $result = this.crearListasReproduccion (login, nombrelista, valores);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // sop_corba/ClienteInt/mostrarListasReproduccion
       {
         sop_corba.ClienteIntPackage.listaReproducionHolder valores = new sop_corba.ClienteIntPackage.listaReproducionHolder ();
         this.mostrarListasReproduccion (valores);
         out = $rh.createReply();
         sop_corba.ClienteIntPackage.dtListaCancHelper.write (out, valores.value);
         break;
       }

       case 6:  // sop_corba/ClienteInt/borrarCancionLista
       {
         String nombreCancion = in.read_string ();
         String nombreLista = in.read_string ();
         boolean $result = false;
         $result = this.borrarCancionLista (nombreCancion, nombreLista);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // sop_corba/ClienteInt/enviarMensaje
       {
         String usuario = in.read_string ();
         String mensaje = in.read_string ();
         this.enviarMensaje (usuario, mensaje);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ClienteInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClienteInt _this() 
  {
    return ClienteIntHelper.narrow(
    super._this_object());
  }

  public ClienteInt _this(org.omg.CORBA.ORB orb) 
  {
    return ClienteIntHelper.narrow(
    super._this_object(orb));
  }


} // class ClienteIntPOA
