package sop_corba;


/**
* sop_corba/ClienteInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

public interface ClienteInt extends ClienteIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final short SIZE = (short)(10);
} // interface ClienteInt
