package sop_corba;


/**
* sop_corba/datosCanciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

public final class datosCanciones implements org.omg.CORBA.portable.IDLEntity
{
  public String tituloCancion = null;
  public String album = null;
  public String nombresCantantes = null;
  public String genero = null;
  public String tiempoDuracion = null;
  public String tamanoArchivo = null;
  public String tipoExtension = null;
  public String codigoCancion = null;
  public String cantidadCopias = null;
  public String topeMinimo = null;
  public String valorCopia = null;

  public datosCanciones ()
  {
  } // ctor

  public datosCanciones (String _tituloCancion, String _album, String _nombresCantantes, String _genero, String _tiempoDuracion, String _tamanoArchivo, String _tipoExtension, String _codigoCancion, String _cantidadCopias, String _topeMinimo, String _valorCopia)
  {
    tituloCancion = _tituloCancion;
    album = _album;
    nombresCantantes = _nombresCantantes;
    genero = _genero;
    tiempoDuracion = _tiempoDuracion;
    tamanoArchivo = _tamanoArchivo;
    tipoExtension = _tipoExtension;
    codigoCancion = _codigoCancion;
    cantidadCopias = _cantidadCopias;
    topeMinimo = _topeMinimo;
    valorCopia = _valorCopia;
  } // ctor

} // class datosCanciones
