package sop_corba;


/**
* sop_corba/datosUsuarios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

public final class datosUsuarios implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public String apellido = null;
  public String login = null;
  public String contrasena = null;

  public datosUsuarios ()
  {
  } // ctor

  public datosUsuarios (String _nombre, String _apellido, String _login, String _contrasena)
  {
    nombre = _nombre;
    apellido = _apellido;
    login = _login;
    contrasena = _contrasena;
  } // ctor

} // class datosUsuarios
