package sop_corba;

/**
* sop_corba/datosUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

public final class datosUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.datosUsuarios value = null;

  public datosUsuariosHolder ()
  {
  }

  public datosUsuariosHolder (sop_corba.datosUsuarios initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.datosUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.datosUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.datosUsuariosHelper.type ();
  }

}
