package sop_corba;


/**
* sop_corba/dtUsuHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

abstract public class dtUsuHelper
{
  private static String  _id = "IDL:sop_corba/dtUsu:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.datosUsuarios that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.datosUsuarios extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = sop_corba.datosUsuariosHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (sop_corba.dtUsuHelper.id (), "dtUsu", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.datosUsuarios read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.datosUsuarios value = null;
    value = sop_corba.datosUsuariosHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.datosUsuarios value)
  {
    sop_corba.datosUsuariosHelper.write (ostream, value);
  }

}
