package sop_corba;


/**
* sop_corba/ServidorIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

public abstract class ServidorIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.ServidorIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ingresoAlSistema", new java.lang.Integer (0));
    _methods.put ("registrarCanciones", new java.lang.Integer (1));
    _methods.put ("modificarDatosCancion", new java.lang.Integer (2));
    _methods.put ("consultarCancion", new java.lang.Integer (3));
    _methods.put ("desactivarCancion", new java.lang.Integer (4));
    _methods.put ("listarCanciones", new java.lang.Integer (5));
    _methods.put ("consultarUsuario", new java.lang.Integer (6));
    _methods.put ("modificarUsuarioA", new java.lang.Integer (7));
    _methods.put ("eliminarUsuario", new java.lang.Integer (8));
    _methods.put ("listarUsuarios", new java.lang.Integer (9));
    _methods.put ("recibirMensaje", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/ServidorInt/ingresoAlSistema
       {
         String login = in.read_string ();
         String clave = in.read_string ();
         boolean $result = false;
         $result = this.ingresoAlSistema (login, clave);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/ServidorInt/registrarCanciones
       {
         sop_corba.datosCanciones valores = sop_corba.dtCancHelper.read (in);
         boolean $result = false;
         $result = this.registrarCanciones (valores);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/ServidorInt/modificarDatosCancion
       {
         String codigoCancion = in.read_string ();
         this.modificarDatosCancion (codigoCancion);
         out = $rh.createReply();
         break;
       }

       case 3:  // sop_corba/ServidorInt/consultarCancion
       {
         String codigoCancion = in.read_string ();
         this.consultarCancion (codigoCancion);
         out = $rh.createReply();
         break;
       }

       case 4:  // sop_corba/ServidorInt/desactivarCancion
       {
         String codigoCancion = in.read_string ();
         this.desactivarCancion (codigoCancion);
         out = $rh.createReply();
         break;
       }

       case 5:  // sop_corba/ServidorInt/listarCanciones
       {
         sop_corba.datosCancionesHolder valores = new sop_corba.datosCancionesHolder ();
         this.listarCanciones (valores);
         out = $rh.createReply();
         sop_corba.dtCancHelper.write (out, valores.value);
         break;
       }

       case 6:  // sop_corba/ServidorInt/consultarUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.consultarUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // sop_corba/ServidorInt/modificarUsuarioA
       {
         String login = in.read_string ();
         this.modificarUsuarioA (login);
         out = $rh.createReply();
         break;
       }

       case 8:  // sop_corba/ServidorInt/eliminarUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.eliminarUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // sop_corba/ServidorInt/listarUsuarios
       {
         sop_corba.datosUsuariosHolder valores = new sop_corba.datosUsuariosHolder ();
         this.listarUsuarios (valores);
         out = $rh.createReply();
         sop_corba.dtUsuHelper.write (out, valores.value);
         break;
       }

       case 10:  // sop_corba/ServidorInt/recibirMensaje
       {
         String usuario = in.read_string ();
         String mensaje = in.read_string ();
         this.recibirMensaje (usuario, mensaje);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ServidorInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServidorInt _this() 
  {
    return ServidorIntHelper.narrow(
    super._this_object());
  }

  public ServidorInt _this(org.omg.CORBA.ORB orb) 
  {
    return ServidorIntHelper.narrow(
    super._this_object(orb));
  }


} // class ServidorIntPOA
