package sop_corba;


/**
* sop_corba/ServidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

public interface ServidorIntOperations 
{
  boolean ingresoAlSistema (String login, String clave);
  boolean registrarCanciones (sop_corba.datosCanciones valores);
  void modificarDatosCancion (String codigoCancion);
  void consultarCancion (String codigoCancion);
  void desactivarCancion (String codigoCancion);
  void listarCanciones (sop_corba.datosCancionesHolder valores);
  boolean consultarUsuario (String login);
  void modificarUsuarioA (String login);
  boolean eliminarUsuario (String login);
  void listarUsuarios (sop_corba.datosUsuariosHolder valores);
  void recibirMensaje (String usuario, String mensaje);
} // interface ServidorIntOperations
