package sop_corba.ClienteIntPackage;


/**
* sop_corba/ClienteIntPackage/arrayCancionesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

abstract public class arrayCancionesHelper
{
  private static String  _id = "IDL:sop_corba/ClienteInt/arrayCanciones:1.0";

  public static void insert (org.omg.CORBA.Any a, int[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static int[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (sop_corba.ClienteInt.SIZE, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (sop_corba.ClienteIntPackage.arrayCancionesHelper.id (), "arrayCanciones", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static int[] read (org.omg.CORBA.portable.InputStream istream)
  {
    int value[] = null;
    value = new int[sop_corba.ClienteInt.SIZE];
    for (int _o0 = 0;_o0 < (sop_corba.ClienteInt.SIZE); ++_o0)
    {
      value[_o0] = istream.read_long ();
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, int[] value)
  {
    if (value.length != (sop_corba.ClienteInt.SIZE))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (sop_corba.ClienteInt.SIZE); ++_i0)
    {
      ostream.write_long (value[_i0]);
    }
  }

}
