package sop_corba.ClienteIntPackage;


/**
* sop_corba/ClienteIntPackage/dtListaCancHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 31 de mayo de 2016 15H38' COT
*/

abstract public class dtListaCancHelper
{
  private static String  _id = "IDL:sop_corba/ClienteInt/dtListaCanc:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ClienteIntPackage.listaReproducion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ClienteIntPackage.listaReproducion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = sop_corba.ClienteIntPackage.listaReproducionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (sop_corba.ClienteIntPackage.dtListaCancHelper.id (), "dtListaCanc", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ClienteIntPackage.listaReproducion read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ClienteIntPackage.listaReproducion value = null;
    value = sop_corba.ClienteIntPackage.listaReproducionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ClienteIntPackage.listaReproducion value)
  {
    sop_corba.ClienteIntPackage.listaReproducionHelper.write (ostream, value);
  }

}
