package sop_corba.ClienteIntPackage;


/**
* sop_corba/ClienteIntPackage/listaReproducion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 27 de mayo de 2016 14H47' COT
*/

public final class listaReproducion implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int res[] = null;

  public listaReproducion ()
  {
  } // ctor

  public listaReproducion (String _nombre, int[] _res)
  {
    nombre = _nombre;
    res = _res;
  } // ctor

} // class listaReproducion
